export { createApp } from './createApp'
export { h } from './h'
export { renderSlots } from './helpers/renderSlot'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
